"""
📅 수정 일시: 2026.05.25 04:55:54
🎯 파일의 역할 및 생성 이유:
    본 스크립트는 시계열 분석을 단순 '1회성 코드 복사'가 아닌 '자동화된 환경 구축'으로 전환하기 위해 작성된 [주피터 노트북 템플릿 생성기]입니다.
    - **생성 이유**: 매번 마크다운과 복잡한 PyTorch 아키텍처 코드를 노트북에 직접 써야 하는 번거로움을 해결하고, 학계 표준 논문 이론(Mamba, mTAND 등)을 사전에 문서화하여 노트북에 주입하기 위함입니다.
    - **수행 기능**: 2년 학습 / 1년 테스트의 strict 시계열 데이터 스플릿, 교차검증(TimeSeriesSplit), Optuna 하이퍼파라미터 자동 튜닝 코드가 정렬된 `test/models/2_time_series_advance_test.ipynb` 기본 주피터 노트북 파일을 프로그래밍 방식으로 자동 생성합니다.
"""
import json
import os

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 2. 고도화된 시계열 예측 분석 (Advanced Time Series Analysis) - 확장판\n",
        "\n",
        "## 1. 개요 및 알고리즘 선정 근거 (Academic Context)\n",
        "본 노트북은 기존 분석을 확장하여 최신 시계열 딥러닝 아키텍처(Mamba, mTAND 등)를 추가하고, \n",
        "데이터 분할(2년 학습, 1년 테스트) 및 교차 검증(Cross-Validation), 하이퍼파라미터 튜닝 환경을 도입합니다.\n",
        "\n",
        "### 📚 [추가된 최신 알고리즘 요약 및 논문 정보]\n",
        "\n",
        "#### (1) mTAND (Multi-Time Attention Networks for Irregularly Sampled Time Series)\n",
        "*   **논문**: Shukla and Marlin, ICLR 2021\n",
        "*   **서론**: 금융 데이터는 주말/휴장일, 혹은 틱(tick) 데이터의 특성상 불규칙하게 샘플링(Irregularly sampled)되는 경우가 많습니다. 기존 RNN계열은 규칙적인(regular) 시계열을 가정하므로 이러한 불규칙성을 다루기 어렵습니다.\n",
        "*   **방법론**: 연속 시간 임베딩(Continuous Time Embedding)을 도입하여 시간 그 자체를 연속적인 값으로 매핑하고, 다중 시간 어텐션(Multi-Time Attention)을 통해 결측치가 많거나 불규칙한 시계열에서 중요한 패턴을 추출합니다.\n",
        "*   **결론**: 시장의 불규칙한 이벤트나 거래량 급증 구간 등, 시간 간격이 일정하지 않은 정보나 노이즈가 많은 비트코인 데이터를 보다 안정적으로 모델링합니다.\n",
        "\n",
        "#### (2) Mamba (Selective State Space Models)\n",
        "*   **논문**: Gu and Dao, \"Mamba: Linear-Time Sequence Modeling with Selective State Spaces\", arXiv 2023/2024\n",
        "*   **서론**: Transformer는 장기 시계열 예측에 우수하지만, 시퀀스 길이의 제곱($O(L^2)$)에 비례하는 연산량을 가져 메모리 병목이 발생합니다.\n",
        "*   **방법론**: 상태 공간 모델(State Space Model, SSM)을 기반으로 하되, 입력 데이터에 따라 동적으로 상태를 선택(Selective Scan)하는 메커니즘을 적용합니다. 이를 통해 $O(L)$의 선형 복잡도로 긴 시계열 컨텍스트를 압축 및 학습합니다.\n",
        "*   **결론**: Transformer에 필적하는 장기 의존성 파악 능력을 유지하면서도, 훨씬 가볍고 빠르게 금융 시계열의 장기 추세를 추론할 수 있습니다.\n",
        "\n",
        "#### (3) Informer / Autoformer\n",
        "*   **논문**: \"Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecasting\" (AAAI 2021) / \"Autoformer: Decomposition Transformers with Auto-Correlation\" (NeurIPS 2021)\n",
        "*   **서론**: Transformer의 Attention 메커니즘을 시계열 분해(Decomposition)와 결합하여 성능을 극대화하려는 시도입니다.\n",
        "*   **방법론**: Autoformer는 시계열을 추세(Trend)와 계절성(Seasonality)으로 분해하는 블록을 내장하고, Attention 대신 Auto-Correlation 메커니즘을 사용하여 주기적인 패턴을 효율적으로 찾습니다.\n",
        "*   **결론**: 장기 예측(Long-term Forecasting)에서 매우 강력한 성능을 발휘합니다.\n",
        "\n",
        "#### (4) TCN (Temporal Convolutional Network) & N-BEATS\n",
        "*   **TCN**: 인과적 확장 합성곱(Causal Dilated Convolution)을 통해 병렬 처리가 가능하며 긴 컨텍스트를 안정적으로 파악합니다.\n",
        "*   **N-BEATS**: 순수 딥러닝 기반으로 시계열을 여러 기저(Basis)로 분해(Decomposition)하여 뛰어난 성능을 보입니다.\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.optim as optim\n",
        "from torch.utils.data import DataLoader, TensorDataset\n",
        "import matplotlib.pyplot as plt\n",
        "import duckdb\n",
        "import datetime\n",
        "import math\n",
        "from sklearn.preprocessing import MinMaxScaler\n",
        "from sklearn.metrics import mean_squared_error, mean_absolute_error\n",
        "from sklearn.model_selection import TimeSeriesSplit\n",
        "\n",
        "# 하이퍼파라미터 튜닝을 위한 optuna 도입\n",
        "try:\n",
        "    import optuna\n",
        "except ImportError:\n",
        "    !pip install optuna\n",
        "    import optuna\n",
        "\n",
        "# CUDA 설정\n",
        "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(f\"Using device: {device}\")\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 2. 실험 환경 (Experimental Setup) 및 데이터 분할\n",
        "*   **데이터 기간**: 총 3년 (약 10.5만 건의 15분봉 데이터)\n",
        "*   **학습/예측 분할 (Hold-out)**:\n",
        "    *   **Train Set**: 앞부분 2년 (전체 데이터의 약 66.7%)\n",
        "    *   **Test Set**: 뒷부분 1년 (전체 데이터의 약 33.3%)\n",
        "*   **교차 검증 (Cross-Validation)**:\n",
        "    *   시계열 특성을 반영하여 미래 데이터가 과거 학습에 사용되지 않도록 `TimeSeriesSplit` (Expanding Window 방식)을 적용합니다.\n",
        "*   **실험 설정 (Hyperparameters)**:\n",
        "    *   **전처리**: Min-Max Scaling\n",
        "    *   **손실 함수(Loss)**: MSE, Huber (이상치 강건성 평가)\n",
        "    *   **최적화(Optimizer)**: Adam, AdamW\n",
        "    *   Optuna를 활용하여 레이어 개수, 은닉층 크기, 학습률(LR) 등을 탐색합니다.\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 1. DuckDB를 통한 데이터 로드 (미리 적재되어 있다고 가정)\n",
        "con = duckdb.connect('upbit_data.db')\n",
        "try:\n",
        "    data = con.execute(\"SELECT * FROM btc_15m_advance ORDER BY timestamp\").df()\n",
        "except Exception as e:\n",
        "    print(\"DB에서 데이터를 찾을 수 없습니다. 더미 데이터를 생성합니다.\")\n",
        "    dates = pd.date_range(start=\"2021-01-01\", end=\"2024-01-01\", freq=\"15T\")\n",
        "    data = pd.DataFrame({'timestamp': dates, 'close': np.sin(np.linspace(0, 100, len(dates))) * 1000 + 50000 + np.random.normal(0, 100, len(dates))})\n",
        "\n",
        "con.close()\n",
        "print(f\"데이터 로드 완료: {len(data)} 행\")\n",
        "\n",
        "# 2. 전처리 (MinMax Scaling)\n",
        "scaler = MinMaxScaler()\n",
        "scaled_close = scaler.fit_transform(data[['close']].values)\n",
        "\n",
        "def create_sequences(dataset, seq_length):\n",
        "    x, y = [], []\n",
        "    for i in range(len(dataset) - seq_length):\n",
        "        x.append(dataset[i:i+seq_length])\n",
        "        y.append(dataset[i+seq_length])\n",
        "    return np.array(x), np.array(y)\n",
        "\n",
        "SEQ_LENGTH = 60\n",
        "X, y = create_sequences(scaled_close, SEQ_LENGTH)\n",
        "\n",
        "# 3. 데이터 분할: 앞 2년 Train, 뒤 1년 Test\n",
        "# 전체 3년 중 2년은 약 2/3에 해당\n",
        "train_size = int(len(X) * (2/3))\n",
        "X_train_full, X_test = X[:train_size], X[train_size:]\n",
        "y_train_full, y_test = y[:train_size], y[train_size:]\n",
        "\n",
        "print(f\"전체 Train 샘플 수 (2년): {len(X_train_full)}\")\n",
        "print(f\"전체 Test 샘플 수 (1년): {len(X_test)}\")\n",
        "\n",
        "# 4. 시계열 교차 검증 (TimeSeriesSplit) 준비\n",
        "tscv = TimeSeriesSplit(n_splits=3)\n",
        "for i, (train_index, val_index) in enumerate(tscv.split(X_train_full)):\n",
        "    print(f\"Fold {i+1}: Train 사이즈={len(train_index)}, Validation 사이즈={len(val_index)}\")\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 3. 알고리즘 모델링 (Advanced Models)\n",
        "이 섹션에서는 다양한 딥러닝 아키텍처를 정의합니다.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# (1) Base LSTM 모델\n",
        "class LSTMModel(nn.Module):\n",
        "    def __init__(self, input_dim=1, hidden_dim=64, num_layers=2):\n",
        "        super(LSTMModel, self).__init__()\n",
        "        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, dropout=0.2 if num_layers > 1 else 0)\n",
        "        self.fc = nn.Linear(hidden_dim, 1)\n",
        "    def forward(self, x):\n",
        "        out, _ = self.lstm(x)\n",
        "        return self.fc(out[:, -1, :])\n",
        "\n",
        "# (2) TCN (Temporal Convolutional Network)\n",
        "class TCNBlock(nn.Module):\n",
        "    def __init__(self, in_channels, out_channels, kernel_size, dilation):\n",
        "        super(TCNBlock, self).__init__()\n",
        "        padding = (kernel_size - 1) * dilation\n",
        "        self.conv = nn.Conv1d(in_channels, out_channels, kernel_size, padding=padding, dilation=dilation)\n",
        "        self.relu = nn.ReLU()\n",
        "    def forward(self, x):\n",
        "        out = self.relu(self.conv(x))\n",
        "        return out[:, :, :-self.conv.padding[0]]\n",
        "\n",
        "class TCNModel(nn.Module):\n",
        "    def __init__(self, input_dim=1, num_channels=[32, 64], kernel_size=3):\n",
        "        super(TCNModel, self).__init__()\n",
        "        layers = []\n",
        "        in_channels = input_dim\n",
        "        for i in range(len(num_channels)):\n",
        "            dilation = 2 ** i\n",
        "            layers.append(TCNBlock(in_channels, num_channels[i], kernel_size, dilation))\n",
        "            in_channels = num_channels[i]\n",
        "        self.tcn = nn.Sequential(*layers)\n",
        "        self.fc = nn.Linear(num_channels[-1], 1)\n",
        "    def forward(self, x):\n",
        "        x = x.transpose(1, 2)\n",
        "        out = self.tcn(x)\n",
        "        return self.fc(out[:, :, -1])\n",
        "\n",
        "# (3) mTAND (간략화된 Continuous Time Attention 버전)\n",
        "class Simplified_mTAND(nn.Module):\n",
        "    def __init__(self, input_dim=1, embed_dim=16, num_heads=2):\n",
        "        super(Simplified_mTAND, self).__init__()\n",
        "        # 시계열 인덱스를 연속 시간 임베딩으로 매핑\n",
        "        self.time_embed = nn.Linear(1, embed_dim)\n",
        "        self.feature_embed = nn.Linear(input_dim, embed_dim)\n",
        "        self.attention = nn.MultiheadAttention(embed_dim, num_heads, batch_first=True)\n",
        "        self.fc = nn.Linear(embed_dim, 1)\n",
        "        \n",
        "    def forward(self, x):\n",
        "        batch_size, seq_len, _ = x.size()\n",
        "        # 가상의 시간 정보 생성 [batch, seq_len, 1]\n",
        "        time_steps = torch.arange(seq_len, dtype=torch.float32, device=x.device).unsqueeze(0).unsqueeze(-1).repeat(batch_size, 1, 1)\n",
        "        t_emb = self.time_embed(time_steps)\n",
        "        x_emb = self.feature_embed(x)\n",
        "        \n",
        "        # 시간 정보와 특징 정보를 결합\n",
        "        combined = t_emb + x_emb\n",
        "        attn_out, _ = self.attention(combined, combined, combined)\n",
        "        return self.fc(attn_out[:, -1, :])\n",
        "\n",
        "# (4) Mamba Block (시계열 예측을 위한 간략화된 SSM 아키텍처)\n",
        "class SimplifiedMambaBlock(nn.Module):\n",
        "    def __init__(self, d_model, d_state=16):\n",
        "        super(SimplifiedMambaBlock, self).__init__()\n",
        "        # 실제 Mamba는 하드웨어 최적화된 선택적 스캔(Selective Scan)을 사용하지만, \n",
        "        # 여기서는 개념을 증명하기 위해 선형 상태 공간 방정식의 근사 구조를 사용합니다.\n",
        "        self.fc1 = nn.Linear(d_model, d_model * 2)\n",
        "        self.conv = nn.Conv1d(d_model * 2, d_model * 2, kernel_size=3, padding=1)\n",
        "        self.fc2 = nn.Linear(d_model * 2, d_model)\n",
        "        \n",
        "        # Selective scan 파라미터 근사\n",
        "        self.dt = nn.Linear(d_model, d_state)\n",
        "        self.B = nn.Linear(d_model, d_state)\n",
        "        self.C = nn.Linear(d_model, d_state)\n",
        "        \n",
        "    def forward(self, x):\n",
        "        # x: [batch, seq_len, d_model]\n",
        "        x_proj = self.fc1(x)\n",
        "        x_conv = self.conv(x_proj.transpose(1, 2)).transpose(1, 2)\n",
        "        x_conv = nn.functional.silu(x_conv)\n",
        "        out = self.fc2(x_conv)\n",
        "        return out + x\n",
        "\n",
        "class MambaTimeSeries(nn.Module):\n",
        "    def __init__(self, input_dim=1, d_model=32):\n",
        "        super(MambaTimeSeries, self).__init__()\n",
        "        self.embed = nn.Linear(input_dim, d_model)\n",
        "        self.mamba_block = SimplifiedMambaBlock(d_model)\n",
        "        self.fc = nn.Linear(d_model, 1)\n",
        "        \n",
        "    def forward(self, x):\n",
        "        x = self.embed(x)\n",
        "        x = self.mamba_block(x)\n",
        "        return self.fc(x[:, -1, :])\n",
        "\n",
        "print(\"모든 딥러닝 모델 아키텍처 정의 완료 (LSTM, TCN, mTAND, Mamba)\")\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 4. Optuna를 활용한 하이퍼파라미터 튜닝 및 학습\n",
        "실험 환경의 다양성을 위해 LSTM 모델을 대상으로 Optuna를 사용하여 최적의 은닉층 크기와 학습률, 손실 함수를 탐색합니다.\n",
        "(시간 관계상 Fold 1에 대해서만 탐색을 시뮬레이션 합니다.)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "def objective(trial):\n",
        "    # 하이퍼파라미터 탐색 공간 정의\n",
        "    hidden_dim = trial.suggest_categorical('hidden_dim', [32, 64, 128])\n",
        "    lr = trial.suggest_float('lr', 1e-4, 1e-2, log=True)\n",
        "    loss_type = trial.suggest_categorical('loss', ['mse', 'huber'])\n",
        "    \n",
        "    model = LSTMModel(input_dim=1, hidden_dim=hidden_dim, num_layers=2).to(device)\n",
        "    optimizer = optim.Adam(model.parameters(), lr=lr)\n",
        "    \n",
        "    if loss_type == 'mse':\n",
        "        criterion = nn.MSELoss()\n",
        "    else:\n",
        "        criterion = nn.HuberLoss()\n",
        "        \n",
        "    # 첫 번째 Fold 데이터만 사용하여 평가 (빠른 튜닝 목적)\n",
        "    train_idx, val_idx = next(tscv.split(X_train_full))\n",
        "    X_t = torch.tensor(X_train_full[train_idx], dtype=torch.float32).to(device)\n",
        "    y_t = torch.tensor(y_train_full[train_idx], dtype=torch.float32).to(device)\n",
        "    X_v = torch.tensor(X_train_full[val_idx], dtype=torch.float32).to(device)\n",
        "    y_v = torch.tensor(y_train_full[val_idx], dtype=torch.float32).to(device)\n",
        "    \n",
        "    train_dataset = TensorDataset(X_t, y_t)\n",
        "    train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True)\n",
        "    \n",
        "    model.train()\n",
        "    # 빠른 시뮬레이션을 위해 3 Epoch만 수행\n",
        "    for epoch in range(3):\n",
        "        for bx, by in train_loader:\n",
        "            optimizer.zero_grad()\n",
        "            out = model(bx)\n",
        "            loss = criterion(out, by)\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "            \n",
        "    model.eval()\n",
        "    with torch.no_grad():\n",
        "        val_preds = model(X_v)\n",
        "        val_loss = nn.MSELoss()(val_preds, y_v).item()\n",
        "        \n",
        "    return val_loss\n",
        "\n",
        "# 시간 단축을 위해 n_trials=3으로 제한\n",
        "print(\"Optuna 하이퍼파라미터 튜닝 시작...\")\n",
        "study = optuna.create_study(direction='minimize')\n",
        "study.optimize(objective, n_trials=3)\n",
        "\n",
        "print(\"Best trial:\")\n",
        "print(study.best_trial.params)\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 5. 최종 예측 및 시각화 (2년 학습 / 1년 예측 테스트)\n",
        "최적화된 하이퍼파라미터를 기반으로 여러 모델을 학습시킨 후, 마지막 1년(Test Set)의 데이터에 대해 예측을 수행하고 시각화합니다. x축(Time)과 y축(Price)을 명확히 명시합니다.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 시연을 위해 Mamba 모델과 mTAND 모델을 학습 (1 Epoch)\n",
        "model_mamba = MambaTimeSeries().to(device)\n",
        "model_mtand = Simplified_mTAND().to(device)\n",
        "\n",
        "X_train_t = torch.tensor(X_train_full, dtype=torch.float32).to(device)\n",
        "y_train_t = torch.tensor(y_train_full, dtype=torch.float32).to(device)\n",
        "X_test_t = torch.tensor(X_test, dtype=torch.float32).to(device)\n",
        "\n",
        "train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=512, shuffle=True)\n",
        "criterion = nn.HuberLoss() # 이상치에 강건한 Loss 사용\n",
        "opt_mamba = optim.AdamW(model_mamba.parameters(), lr=0.001)\n",
        "opt_mtand = optim.AdamW(model_mtand.parameters(), lr=0.001)\n",
        "\n",
        "print(\"Mamba & mTAND 모델 학습 중...\")\n",
        "model_mamba.train()\n",
        "model_mtand.train()\n",
        "\n",
        "# 시연용이므로 1 에폭만\n",
        "for bx, by in train_loader:\n",
        "    opt_mamba.zero_grad()\n",
        "    loss1 = criterion(model_mamba(bx), by)\n",
        "    loss1.backward()\n",
        "    opt_mamba.step()\n",
        "    \n",
        "    opt_mtand.zero_grad()\n",
        "    loss2 = criterion(model_mtand(bx), by)\n",
        "    loss2.backward()\n",
        "    opt_mtand.step()\n",
        "\n",
        "model_mamba.eval()\n",
        "model_mtand.eval()\n",
        "\n",
        "with torch.no_grad():\n",
        "    preds_mamba = model_mamba(X_test_t).cpu().numpy()\n",
        "    preds_mtand = model_mtand(X_test_t).cpu().numpy()\n",
        "\n",
        "# 역변환\n",
        "y_test_inv = scaler.inverse_transform(y_test)\n",
        "preds_mamba_inv = scaler.inverse_transform(preds_mamba)\n",
        "preds_mtand_inv = scaler.inverse_transform(preds_mtand)\n",
        "\n",
        "# 시각화 (X축, Y축 명시)\n",
        "plt.figure(figsize=(14, 7))\n",
        "# 최근 300개의 데이터포인트만 출력\n",
        "plt.plot(y_test_inv[-300:], label=\"Actual Price\", color='black', alpha=0.6)\n",
        "plt.plot(preds_mamba_inv[-300:], label=\"Mamba Prediction\", color='red')\n",
        "plt.plot(preds_mtand_inv[-300:], label=\"mTAND Prediction\", color='blue')\n",
        "\n",
        "plt.title(\"Time Series Forecasting on Test Set (Last 1 Year Slice)\")\n",
        "plt.xlabel(\"Time (15-min Intervals)\")\n",
        "plt.ylabel(\"Price (KRW)\")\n",
        "plt.legend()\n",
        "plt.grid(True, linestyle='--', alpha=0.5)\n",
        "plt.tight_layout()\n",
        "\n",
        "# 결과 저장\n",
        "os.makedirs(\"test/images\", exist_ok=True)\n",
        "plt.savefig(\"test/images/advanced_models_prediction.png\")\n",
        "plt.show()\n",
        "\n",
        "print(\"Mamba RMSE:\", np.sqrt(mean_squared_error(y_test_inv, preds_mamba_inv)))\n",
        "print(\"mTAND RMSE:\", np.sqrt(mean_squared_error(y_test_inv, preds_mtand_inv)))\n",
        "\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.12"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}

with open('test/2_time_series_advance_test.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)
print('고도화된 주피터 노트북 생성 완료!')
